baseURL = "https://cremaontop.com/"
disablePathToLower = true
languageCode = "en-us"
title = "Crema on Top - Brewing Espresso at Home"
theme= "tale"
googleAnalytics = "G-9DZF47DQEX"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/pages/about/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/"
    weight = 0